/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ece.edu.espe.cyberplanetasystem.view;

/**
 *
 * @author Usuario
 */
public class FrmCyberPlanetaMain extends javax.swing.JFrame {

    /**
     * Creates new form FrmCyberPlanetaMain
     */
    public FrmCyberPlanetaMain() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        mnuCyberPlaneta = new javax.swing.JMenu();
        itmLogout = new javax.swing.JMenuItem();
        itmExit = new javax.swing.JMenuItem();
        mnuTaxpayer = new javax.swing.JMenu();
        mnuClassificationAgenda = new javax.swing.JMenu();
        mnuPricingSystem = new javax.swing.JMenu();
        itmTaxProcessCosst = new javax.swing.JMenuItem();
        itmTotalIcome = new javax.swing.JMenuItem();
        itmCAGR = new javax.swing.JMenuItem();
        mnuHelp = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mnuCyberPlaneta.setText("CyberPlaneta");

        itmLogout.setText("LogOut");
        mnuCyberPlaneta.add(itmLogout);

        itmExit.setText("Exit");
        itmExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmExitActionPerformed(evt);
            }
        });
        mnuCyberPlaneta.add(itmExit);

        jMenuBar1.add(mnuCyberPlaneta);

        mnuTaxpayer.setText("Taxpayer");
        jMenuBar1.add(mnuTaxpayer);

        mnuClassificationAgenda.setText("Classification Agenda");
        jMenuBar1.add(mnuClassificationAgenda);

        mnuPricingSystem.setText("Pricing System");

        itmTaxProcessCosst.setText("Calculate Tax Process Cost");
        itmTaxProcessCosst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmTaxProcessCosstActionPerformed(evt);
            }
        });
        mnuPricingSystem.add(itmTaxProcessCosst);

        itmTotalIcome.setText("Review Total Income");
        mnuPricingSystem.add(itmTotalIcome);

        itmCAGR.setText("Calculate CAGR");
        mnuPricingSystem.add(itmCAGR);

        jMenuBar1.add(mnuPricingSystem);

        mnuHelp.setText("Help");
        jMenuBar1.add(mnuHelp);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 551, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itmTaxProcessCosstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmTaxProcessCosstActionPerformed
        FrmTaxProcessCost frmtaxProcessCostCalculator = new FrmTaxProcessCost();
        this.setVisible(false);
        frmtaxProcessCostCalculator.setVisible(true);
        
    }//GEN-LAST:event_itmTaxProcessCosstActionPerformed

    private void itmExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_itmExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmCyberPlanetaMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmCyberPlanetaMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmCyberPlanetaMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmCyberPlanetaMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmCyberPlanetaMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem itmCAGR;
    private javax.swing.JMenuItem itmExit;
    private javax.swing.JMenuItem itmLogout;
    private javax.swing.JMenuItem itmTaxProcessCosst;
    private javax.swing.JMenuItem itmTotalIcome;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu mnuClassificationAgenda;
    private javax.swing.JMenu mnuCyberPlaneta;
    private javax.swing.JMenu mnuHelp;
    private javax.swing.JMenu mnuPricingSystem;
    private javax.swing.JMenu mnuTaxpayer;
    // End of variables declaration//GEN-END:variables
}
