package ec.edu.espe.registrationsystem;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author ChelooWs
 */
public class FrmRegistrationSystem extends javax.swing.JFrame {

    /**
     * Creates new form FrmRegistrationSystem
     */
    public FrmRegistrationSystem() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuRegistrationSystem = new javax.swing.JMenu();
        itmLogout = new javax.swing.JMenuItem();
        itmExit = new javax.swing.JMenuItem();
        mnuStudents = new javax.swing.JMenu();
        itmShowGratuititi = new javax.swing.JMenuItem();
        itmShowProumedious = new javax.swing.JMenuItem();
        itmTutor = new javax.swing.JMenu();
        mnuStaff = new javax.swing.JMenu();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mnuRegistrationSystem.setText("Sistema de Registro");

        itmLogout.setText("Logout");
        itmLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmLogoutActionPerformed(evt);
            }
        });
        mnuRegistrationSystem.add(itmLogout);

        itmExit.setText("Exit");
        itmExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmExitActionPerformed(evt);
            }
        });
        mnuRegistrationSystem.add(itmExit);

        jMenuBar1.add(mnuRegistrationSystem);

        mnuStudents.setText("Estudiantes");

        itmShowGratuititi.setText("Ver Gratuidad");
        itmShowGratuititi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmShowGratuititiActionPerformed(evt);
            }
        });
        mnuStudents.add(itmShowGratuititi);

        itmShowProumedious.setText("Ver Promedios");
        itmShowProumedious.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmShowProumediousActionPerformed(evt);
            }
        });
        mnuStudents.add(itmShowProumedious);

        jMenuBar1.add(mnuStudents);

        itmTutor.setText("Profesor");
        jMenuBar1.add(itmTutor);

        mnuStaff.setText("Administrativo");
        jMenuBar1.add(mnuStaff);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 369, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itmShowProumediousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmShowProumediousActionPerformed
        FrmVerPromedios frmVerPromedios = new FrmVerPromedios();
        this.setVisible(false);
        frmVerPromedios.setVisible(true);
    }//GEN-LAST:event_itmShowProumediousActionPerformed

    private void itmLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmLogoutActionPerformed
        FrmLogin fmrFrmLogin = new FrmLogin();
        this.setVisible(false);
        fmrFrmLogin.setVisible(true);
        
    }//GEN-LAST:event_itmLogoutActionPerformed

    private void itmExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_itmExitActionPerformed

    private void itmShowGratuititiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmShowGratuititiActionPerformed
        FrmVerGratuidad fmrVerGratuidad = new FrmVerGratuidad();
        this.setVisible(false);
        fmrVerGratuidad.setVisible(true);
    }//GEN-LAST:event_itmShowGratuititiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmRegistrationSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmRegistrationSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmRegistrationSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmRegistrationSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmRegistrationSystem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem itmExit;
    private javax.swing.JMenuItem itmLogout;
    private javax.swing.JMenuItem itmShowGratuititi;
    private javax.swing.JMenuItem itmShowProumedious;
    private javax.swing.JMenu itmTutor;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenu mnuRegistrationSystem;
    private javax.swing.JMenu mnuStaff;
    private javax.swing.JMenu mnuStudents;
    // End of variables declaration//GEN-END:variables
}
